# permissions for end users to view servers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: server-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: customresource
    app.kubernetes.io/part-of: customresource
    app.kubernetes.io/managed-by: kustomize
  name: server-viewer-role
rules:
- apiGroups:
  - cloudcontroller.crd.example.com
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudcontroller.crd.example.com
  resources:
  - servers/status
  verbs:
  - get
